#!/bin/bash

# Скрипт для генерации заголовочного файла version.hpp из git тегов
# Соответствует документации docs/workflow/git_rules.md

set -e

OUTPUT_FILE="${1:-include/version.hpp}"

# Получаем версию из git тегов
if git describe --tags --abbrev=0 2>/dev/null; then
    VERSION=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//')
    FULL_VERSION=$(git describe --tags --long --dirty 2>/dev/null | sed 's/^v//')
else
    # Если тегов нет, используем 0.0.0-dev
    VERSION="0.0.0"
    FULL_VERSION="0.0.0-dev-$(git rev-parse --short HEAD 2>/dev/null || echo 'unknown')"
fi

# Получаем дополнительную информацию
GIT_COMMIT=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
GIT_COMMIT_SHORT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Генерируем заголовочный файл
cat > "$OUTPUT_FILE" << EOF
// GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate_version.sh
// Build date: ${BUILD_DATE}

#ifndef BNF_PARSER_VERSION_HPP
#define BNF_PARSER_VERSION_HPP

#include <string>

namespace bnf_parser {
namespace version {

// Версия из git тегов (semantic versioning)
constexpr const char* VERSION = "${VERSION}";

// Полная версия с git информацией
constexpr const char* FULL_VERSION = "${FULL_VERSION}";

// Git commit hash
constexpr const char* GIT_COMMIT = "${GIT_COMMIT}";
constexpr const char* GIT_COMMIT_SHORT = "${GIT_COMMIT_SHORT}";

// Дата сборки
constexpr const char* BUILD_DATE = "${BUILD_DATE}";

// Описание версии
inline std::string getVersionString() {
    return std::string(VERSION) + " - Full BNF/EBNF Compliance";
}

// Полная информация о версии
inline std::string getFullVersionInfo() {
    return std::string("BNF Parser v") + FULL_VERSION + 
           " (commit: " + GIT_COMMIT_SHORT + ", built: " + BUILD_DATE + ")";
}

} // namespace version
} // namespace bnf_parser

#endif // BNF_PARSER_VERSION_HPP
EOF

echo "Generated version header: $OUTPUT_FILE"
echo "Version: $VERSION ($FULL_VERSION)"

