#!/bin/bash

# Generates version.hpp from git tags
# Matches docs/workflow/git_rules.md

set -e

OUTPUT_FILE="${1:-include/version.hpp}"

# Read version from git tags
if git describe --tags --abbrev=0 2>/dev/null; then
    VERSION=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//')
    FULL_VERSION=$(git describe --tags --long --dirty 2>/dev/null | sed 's/^v//')
else
    # If no tags, use 0.0.0-dev
    VERSION="0.0.0"
    FULL_VERSION="0.0.0-dev-$(git rev-parse --short HEAD 2>/dev/null || echo 'unknown')"
fi

# Additional information
GIT_COMMIT=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
GIT_COMMIT_SHORT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Generate header
cat > "$OUTPUT_FILE" << EOF
// GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate_version.sh
// Build date: ${BUILD_DATE}

#ifndef BNF_PARSER_GENERATOR_VERSION_HPP
#define BNF_PARSER_GENERATOR_VERSION_HPP

#include <string>

namespace bnf_parser_generator {
namespace version {

// Version from git tags (semantic versioning)
constexpr const char* VERSION = "${VERSION}";

// Full version with git info
constexpr const char* FULL_VERSION = "${FULL_VERSION}";

// Git commit hash
constexpr const char* GIT_COMMIT = "${GIT_COMMIT}";
constexpr const char* GIT_COMMIT_SHORT = "${GIT_COMMIT_SHORT}";

// Build date
constexpr const char* BUILD_DATE = "${BUILD_DATE}";

// Version description
inline std::string getVersionString() {
    return std::string(VERSION) + " - BNF Parser Generator";
}

// Full version info
inline std::string getFullVersionInfo() {
    return std::string("BNF Parser Generator v") + FULL_VERSION + 
           " (commit: " + GIT_COMMIT_SHORT + ", built: " + BUILD_DATE + ")";
}

} // namespace version
} // namespace bnf_parser_generator

#endif // BNF_PARSER_GENERATOR_VERSION_HPP
EOF

echo "Generated version header: $OUTPUT_FILE"
echo "Version: $VERSION ($FULL_VERSION)"

