// GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate_version.sh
// Build date: 2025-10-10 21:24:21 UTC

#ifndef BNF_PARSER_VERSION_HPP
#define BNF_PARSER_VERSION_HPP

#include <string>

namespace bnf_parser {
namespace version {

// Версия из git тегов (semantic versioning)
constexpr const char* VERSION = "0.0.0";

// Полная версия с git информацией
constexpr const char* FULL_VERSION = "0.0.0-dev-a75d921";

// Git commit hash
constexpr const char* GIT_COMMIT = "a75d921ebc63b500cca3fdc958a45034494ce1a9";
constexpr const char* GIT_COMMIT_SHORT = "a75d921";

// Дата сборки
constexpr const char* BUILD_DATE = "2025-10-10 21:24:21 UTC";

// Описание версии
inline std::string getVersionString() {
    return std::string(VERSION) + " - Full BNF/EBNF Compliance";
}

// Полная информация о версии
inline std::string getFullVersionInfo() {
    return std::string("BNF Parser v") + FULL_VERSION + 
           " (commit: " + GIT_COMMIT_SHORT + ", built: " + BUILD_DATE + ")";
}

} // namespace version
} // namespace bnf_parser

#endif // BNF_PARSER_VERSION_HPP
